### PR TITLE
Fix console build info in README.md

### PR DESCRIPTION
**Pull request by turboMaCk**
- [x] Fix path to new package version
    Note: Actual version is `1.1.0`
- [x] Fix permission issue by calling script using `sh`
    Note: I believe taht this is the best day how to
    fix all possible issues between various OS (Unixes)

Hello!
====

This is just update of README.md. Description is in commit message.

### CODE REVIEW

**Comment by turboMaCk** [comment]
Bonus: use gulp.js to automate tests and build:

https://gist.github.com/turboMaCk/e2e5bdaee255cd2d1488

**Comment by mgold** [comment]
:+1:

**Comment by turboMaCk** [comment]
@deadfoxygrandpa Any feedback?

**Comment by deadfoxygrandpa** [comment]
Thanks, and I'll add the gulp.js stuff to the readme too.

**Pull request merged**
